config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'events#index'

  resources :users, only: %i[show edit update]
  resources :events do
    resources :comments, only: %i[create destroy]
    resources :subscriptions, only: %i[create destroy]
    resources :photos, only: %i[create destroy]

    post :show, on: :member
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers,
           through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  validates :title, presence: true, length: { maximum: 255 }
  validates :address, presence: true
  validates :datetime, presence: true, inclusion: { in: (Time.now..) }
  validates :user, presence: true
  validates :pincode, length: { is: 3 }, format: /\A\p{Digit}{3}\z/, if: -> { pincode.present? }

  def visitors
    (subscribers + [user]).uniq
  end

  def visitors_emails
    (subscriptions.map(&:user_email) + [user.email]).uniq
  end

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_event, only: [:show]
  before_action :set_current_user_event, only: [:edit, :update, :destroy]
  before_action :password_guard!, only: [:show]

  def index
    @events = Event.all
  end

  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
  end

  def edit
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to event_path(@event), notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event), notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: t('.success')
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def set_current_user_event
    @event = current_user.events.find(params[:id])
  end

  def event_params
    params.require(:event)
          .permit(:title, :address, :description, :datetime, :photo, :pincode)
  end

  def password_guard!
    return true if @event.pincode.blank?
    return true if signed_in? && current_user == @event.user

    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    pincode = cookies.permanent["events_#{@event.id}_pincode"]
    unless @event.pincode_valid?(pincode)
      if params[:pincode].present?
        flash.now[:alert] = t('.show.wrong_pincode')
      end
      render :password_form
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<%# Паршиал для отображения инфы об отдельном событии %>
<div class="col-sm-6 col-md-4">
  <div class="thumbnail text-left mb-3">

    <%= content_tag 'div', '', class: 'event-background',
      style: "background-image: url(#{event_photo(event)})" %>

    <div class="event-info-inner">
      <div class="card-body">
        <div class="event-description">
          <h3 class="text-break"><%= link_to event.title, event_path(event) %></h3>
          <h3><small><%= l(event.datetime, format: :short) %></small></h3>
          <div class="buffer-both"><%= event.address %></div>
        </div>
        <div>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: 'img-icon-small', title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class="col-md-6 my-3">
  <%= simple_form_for(@event) do |f| %>
    <%= f.error_notification %>

    <%= f.input :title %>
    <%= f.input :address %>
    <%= f.input :datetime, as: :string,
                input_html: {
                  id: 'datepicker',
                  autocomplete: 'off'
                } %>
    <%= f.input :description %>
    <%= f.input :pincode %>

    <%= f.button :submit, t('app.save'), class: 'btn-primary' %>
    или <%= link_to t('app.back'), :back, class: 'text-decoration-none' %>
  <% end %>
</div>

app/views/events/edit.html.erb
<h1><%= t('.one') %></h1>

<div class="row">
  <%= render 'form' %>
</div>

app/views/events/index.html.erb
<h1><%= t('.many') %></h1>

<div class="buffer-both">
  <%= link_to t('events.new.one'), new_event_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1><%= t('.one') %></h1>

<div class="row">
  <%= render 'form' %>
</div>

app/views/events/password_form.html.erb
<div class="col-md-6 my-3">
  <h1><%= t('.title') %></h1>

  <%= simple_form_for('', method: :post) do |f| %>
    <%= f.error_notification %>

    <%= f.input :pincode, label: t('activerecord.attributes.event.pincode') %>

    <div class="actions mb-3">
      <%= f.button :submit, t('app.save'), class: 'btn-primary' %>
    </div>
  <% end %>

  <%= link_to t('app.to_index'), events_path %>
</div>

app/views/events/show.html.erb
<div class="event my-3">
  <div class="event-info row rounded">
    <div class="col-md-12">
      <%= content_tag 'div', '', class: 'event-background',
        style: "background-image: url(#{event_photo(@event)})" %>

      <div class="event-info-inner row">
        <div class="col-md-12">
          <div class="row">
            <div class="col-md-6 d-flex flex-column">
              <div class="event-description mt-3">
                <h1><%= @event.title %></h1>
                <h3><%= l(@event.datetime, format: :long) %></h3>
                <h3><small><%= link_to @event.address,
                                       "https://yandex.ru/maps/?text=#{@event.address}", class: 'text-decoration-none' %></small></h3>
                <p><%= @event.description %></p>
              </div>
              <% if current_user_can_edit?(@event) %>
                <div class="mt-auto mb-3">
                  <%= link_to t('app.change'), edit_event_path(@event), class: 'btn btn-primary' %>
                  <%= link_to t('app.delete'),
                              event_path(@event), method: :delete,
                              data: {confirm: t('.confirm')}, class: 'btn btn-danger ml-3' %>
                </div>
              <% end %>
            </div>
            <div class="col-md-6 buffer-both">
              <div id="map" data-address="<%= @event.address %>"></div>
            </div>
          </div>


        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <div class="event-photos">
      <div class="event-photos-gallery mb-3">
        <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
      </div>
      <% if @event.visitors.include?(current_user) %>
        <div class="event-photo-form">
          <%= render partial: 'photos/form',
                     locals: { photo: @new_photo || @event.photos.build } %>
        </div>
      <% end %>
    </div>

    <div class="event-comments">
      <%= render partial: 'comments/form',
                 locals: {comment: @new_comment || @event.comments.build} %>
      <div class="buffer-both">
        <%= render partial: 'comments/comment',
                   collection: @event.comments.except(@new_comment).order(created_at: :desc) %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <div class="event-owner">
      <h4><%= t('app.host') %></h4>
      <p><%= render partial: 'users/user', object: @event.user %></p>
    </div>

    <% if @event.subscriptions.exists? %>
      <div class="event-subscriptions">
        <h4><%= t('app.subscribers') %></h4>
        <div>
          <p>
            <%= render partial: 'subscriptions/subscription',
                       collection: @event.subscriptions.except(@new_subscription) %>
          </p>
        </div>
      </div>
    <% end %>

    <% unless current_user_can_edit?(@event) || @event.subscribers.include?(current_user) %>
      <div class="event-subscription-form">
        <h4><%= t('app.subscribe') %></h4>
        <div>
          <%= render partial: 'subscriptions/form', locals: {
            subscription: @new_subscription || @event.subscriptions.build
          } %>
        </div>
      </div>
    <% end %>
  </div>
</div>